---
title: Abstract for Tile Sets Generated by Hadamard Submatrices of Fourier Matrices
author: Troy Wiegand with Faculty Mentor Dr. John Herr
output: pdf_document
---


Hadamard matrices are a class of $n$ by $n$ sized matrices whose entries have unit modulus and the property that the matrix times its adjoint is $n$ times the identity matrix.
Fourier matrices are Hadamard matrices where the $(j,k)$th entry of an $n$ by $n$ matrix is $e^{\frac{2 \pi i j k}{n}}$. 

This project looks into when a submatrix of a Fourier matrix is still Hadamard and the relationships between Hadamard submatrices.

Furthermore, I am examining the sets of rows from Hadamard submatrices that share the columns to see if they all "tile the integers" in the same manner.

This process of searching for Hadamard submatrices becomes increasingly computationally intensive as we increase the size of the Fourier matrix. 
Exploring symmetry and other properties of Hadamard matrices will allow us to find submatrices from larger Fourier matrices. 
